package com.atomic.kotlin.chapter02.Exceptions

fun erroneousCode() {
    // val i = "1$".toInt()
}

fun main() {
    erroneousCode()
}